development:
  clients:
    default:
      database: btb_dev
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: btb_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  env: <%= ENV['MONGOHQ_URL'] %>