development:
  sessions:
    default:
      database: btb_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: btb_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>