production:
  sessions:
    default:
      uri: <%= ENV['DATABASE_URL'] %>
      options:
        w: 1
        read: primary
        max_retries: 1
        retry_interval: 0
development:
  sessions:
    default:
      database: btb_dev
      hosts:
        - localhost:27017
      options:
        w: 1
        read: primary
        max_retries: 1
        retry_interval: 0
  options:
    use_activesupport_time_zone: true
    use_utc: false
test:
  sessions:
    default:
      database: btb_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
